### ISSUE TITLE
XML tree changes lost after parsing new XML string

### ISSUE THREAD

**Issue by pdwilson12** [mirod/xmltwig#6]
Looks like similar garbage-collection issue as fixed in 3.42.  When I create a new XML element vis XML::Twig->new()->parse() and then make changes to it, the changes vanish when I parse the next XML string.

Here's a script that demonstrates the problem:
# 

```
#!/usr/bin/perl
use strict;
use warnings;

use XML::Twig;

sub parseXML {
    my $xmlString = shift;

    my $twig = XML::Twig->new();
    $twig->parse($xmlString);
    return $twig->root();      #  Add a ->copy() to fix
}

#  Create a new XML object and insert an element into it
my $a = parseXML("<root></root>");
my $b = parseXML("<inserted_element/>");
$b->paste('last_child', $a);

#  Create a new XML object and record the XML string of the original object before and after parsing
#  $a should be identical before and after, but it reverts to its original (pre-insert) value when
#  a new XML string is parsed.
my $original_xml = $a->sprint();
print "\$a = $original_xml\n";
my $c = parseXML("<c/>");
my $new_xml = $a->sprint();
print "\$a = $new_xml\n";

if( $original_xml ne $new_xml ) {
    print "*** XML changed ***\n";
}
```

**Comment by mirod** [comment]
I am sorry I never saw this bug report. The problem is with scoping. The parseXML sub returns the root of the tree without removing it from the original XML::Twig object. So the XML::Twig object is not discarded, since its root is still in scope. As you saw using copy gets rid of the problem. cut is a cheaper way to do it, this way the element does not belong to the tree anymore, and the tree is discarded when leaving the scope of the sub.
